server:
  port: 28081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo2?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/,http://eureka-server3:8763/eureka/
  instance:
    instance-id: eureka-provider-28081
    ip-address: true
info:
  app:
    name: yang-eureka-provider
    description: SpringCloud服务提供方案
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@